### ISSUE TITLE
Data Availability

### ISSUE THREAD

**Issue by QTiiiiiiiiiiii** [masashi-hatano/MM-CDFSL#1]
Hello! Could you please share the relevant data of pose and flow?

**Comment by masashi-hatano** [comment]
Hi,
I will upload the data, but currently facing an issue.
Please be patient until the upload is finished.

**Comment by masashi-hatano** [comment]
@QTiiiiiiiiiiii 
Hello, 
I finished uploading the preprocessed data to the hub!
The data is [here](https://huggingface.co/datasets/masashi-hatano/MM-CDFSL/tree/main).

**Comment by QTiiiiiiiiiiii** [comment]
Thank you for uploading the data. I truly appreciate your effort and support.

**Comment by xixi00001** [comment]
> Thank you for uploading the data. I truly appreciate your effort and support.

Hello, have you successfully run the code yet? Are you Chinese? Can we add each other on WeChat for further communication?
