### ISSUE TITLE
How many GPU are needed for the training of the whole model?

### ISSUE THREAD

**Issue by Saunak626** [masashi-hatano/MM-CDFSL#2]
config_pretrain.yaml
accelerator: gpu
devices: [0, 1]

Hello! Is this only using two graphics cards? How much video memory?

**Comment by masashi-hatano** [comment]
Yes, we use two GPUs during training due to the resource limit.
But, it won't take much time to train as we initialize with the pre-trained weight trained on the Kinetics dataset.

**Comment by xgiaogiao** [comment]
Thanks for your great work! Based on the dataset links you've shared, it appears that the RGB modality is missing for all four datasets. Could you kindly confirm if this is the case? Additionally, could you provide an estimate of the total storage space required to download all three modalities (RGB, optical flow and hand pose heatmap) for all four datasets?

**Comment by xgiaogiao** [comment]
Hello! I noticed you mentioned that "we use two GPUs with 24GB during training due to the resource limit. But, it won't take much time to train as we initialize with the pre-trained weight trained on the Kinetics dataset." I am reaching out to inquire about the approximate time required per epoch when training on the EPIC dataset under similar settings. With my setup of two 24GB GPUs (NVIDIA 3090), each epoch is taking approximately 3 hours to complete. Could you kindly share how long it typically took for you per epoch?

**Comment by masashi-hatano** [comment]
The training time is approximately half a day for the pretraining stage on the Ego4D-EPIC scenario and 1.5 days for the multimodal distillation stage.
We used two RTX 4090 GPUs for these trainings.

**Comment by 000111-feng** [comment]
> config_pretrain.yaml accelerator: gpu devices: [0, 1]
> 
> Hello! Is this only using two graphics cards? How much video memory?

Hello! I encountered some issues while trying to obtain the code. I found out from your homepage that you are Chinese, can I communicate with you about it?

**Comment by masashi-hatano** [comment]
As there is no issue here, I close this issue

**Comment by xixi00001** [comment]
> Hello! I noticed you mentioned that "we use two GPUs with 24GB during training due to the resource limit. But, it won't take much time to train as we initialize with the pre-trained weight trained on the Kinetics dataset." I am reaching out to inquire about the approximate time required per epoch when training on the EPIC dataset under similar settings. With my setup of two 24GB GPUs (NVIDIA 3090), each epoch is taking approximately 3 hours to complete. Could you kindly share how long it typically took for you per epoch?

Hello, have you successfully run the code yet? Are you Chinese? Can we add each other on WeChat for further communication?

**Comment by xixi00001** [comment]
> config_pretrain.yaml accelerator: gpu devices: [0, 1]
> 
> Hello! Is this only using two graphics cards? How much video memory?

Hello, please forgive me for taking the liberty to message you. Could you please share your email address? I have a few questions to ask.
