### ISSUE TITLE
Dataset modality missing and total storage space for memory

### ISSUE THREAD

**Issue by xgiaogiao** [masashi-hatano/MM-CDFSL#3]
Thanks for your great work! Based on the dataset links you've shared, it appears that the RGB modality is missing for all four datasets. Could you kindly confirm if this is the case? Additionally, could you provide an estimate of the total storage space required to download all three modalities (RGB, optical flow and hand pose heatmap) for all four datasets?

**Comment by masashi-hatano** [comment]
We didn't upload the RGB frames to avoid the violence of dataset usage. (For instance, Ego4D requires access tokens for each individual).
However, RGB video can be downloaded from the original websites.
As for the amount of storage required, it is approximately ~2TB.

**Comment by xgiaogiao** [comment]
Thank you very much for your reply!

**Comment by xixi00001** [comment]
> Thanks for your great work! Based on the dataset links you've shared, it appears that the RGB modality is missing for all four datasets. Could you kindly confirm if this is the case? Additionally, could you provide an estimate of the total storage space required to download all three modalities (RGB, optical flow and hand pose heatmap) for all four datasets?

Hello, please forgive me for taking the liberty to message you. Could you please share your email address? I have a few questions to ask.
