### ISSUE TITLE
About the RGB_frames of WEAR dataset 

### ISSUE THREAD

**Issue by xgiaogiao** [masashi-hatano/MM-CDFSL#4]
Hello! I would like to extend my sincere appreciation for your work. Now I am in the process of reproducing your experiments, and I have encountered some difficulties specifically related to accessing the RGB frames (rgb_frames) within the WEAR dataset. The dataset files I found include:
Annotations (>1MB): JSON files with annotations per subject, following the THUMOS14 format.
Processed Data (15GB): Precomputed features (I3D, inertial, and combined) per subject in .npy format.
Raw Data (130GB): Per-subject raw video data in .mp4 format and inertial data in .csv format.
However, I was unable to locate the RGB frames in .jpg format, as described. Could you kindly advise if there is an additional step or preprocessing method needed to extract these frames from the provided data files? Any guidance on this matter would be immensely helpful.Thank you very much for your time!

**Comment by masashi-hatano** [comment]
We extracted image frames from the raw video data in .jpg format.
As for the resolution of the image, we resized the height to 256 and kept the aspect ratio to save data usage.

**Comment by xgiaogiao** [comment]
Thank you once again for your helpful response regarding frame extraction and resolution.
I do have a follow-up question: I noticed that the target_sampling_rate in your provided code for the WEAR dataset is set to 8. Could you please clarify if this indicates that every 8th frame was sampled? Additionally, if possible, could you  share the specific code used for converting the raw videos into .jpg frames,please? Having access to this code would greatly help me.Thank you very much for your help!

**Comment by xgiaogiao** [comment]
Thank you once again for your helpful response regarding frame extraction and resolution.
I do have a follow-up question: I noticed that the target_sampling_rate in your provided code for the WEAR dataset is set to 8. Could you please clarify if this indicates that every 8th frame was sampled? Additionally, if possible, could you share the specific code used for converting the raw videos into .jpg frames? Having access to this code would greatly help me.If it is convenient, could you please send the code to my email at 23011211034@stu.xidian.edu.cn? I would be very grateful for your help. Thank you very much for your help!

**Comment by 000111-feng** [comment]
> Thank you once again for your helpful response regarding frame extraction and resolution. I do have a follow-up question: I noticed that the target_sampling_rate in your provided code for the WEAR dataset is set to 8. Could you please clarify if this indicates that every 8th frame was sampled? Additionally, if possible, could you share the specific code used for converting the raw videos into .jpg frames? Having access to this code would greatly help me.If it is convenient, could you please send the code to my email at [23011211034@stu.xidian.edu.cn](mailto:23011211034@stu.xidian.edu.cn)? I would be very grateful for your help. Thank you very much for your help!

Hello!  I encountered some issues while trying to obtain the code. I found out from your homepage that you are Chinese, can I communicate with you about it?

**Comment by xgiaogiao** [comment]
> > Thank you once again for your helpful response regarding frame extraction and resolution. I do have a follow-up question: I noticed that the target_sampling_rate in your provided code for the WEAR dataset is set to 8. Could you please clarify if this indicates that every 8th frame was sampled? Additionally, if possible, could you share the specific code used for converting the raw videos into .jpg frames? Having access to this code would greatly help me.If it is convenient, could you please send the code to my email at [23011211034@stu.xidian.edu.cn](mailto:23011211034@stu.xidian.edu.cn)? I would be very grateful for your help. Thank you very much for your help!
> 
> Hello! I encountered some issues while trying to obtain the code. I found out from your homepage that you are Chinese, can I communicate with you about it?

Of course.My QQ number is 3489574613,you can contact me.

**Comment by masashi-hatano** [comment]
> I do have a follow-up question: I noticed that the target_sampling_rate in your provided code for the WEAR dataset is set to 8. Could you please clarify if this indicates that every 8th frame was sampled? 
Yes, we sample every eight frames for this dataset.

**Comment by 000111-feng** [comment]
> > > Thank you once again for your helpful response regarding frame extraction and resolution. I do have a follow-up question: I noticed that the target_sampling_rate in your provided code for the WEAR dataset is set to 8. Could you please clarify if this indicates that every 8th frame was sampled? Additionally, if possible, could you share the specific code used for converting the raw videos into .jpg frames? Having access to this code would greatly help me.If it is convenient, could you please send the code to my email at [23011211034@stu.xidian.edu.cn](mailto:23011211034@stu.xidian.edu.cn)? I would be very grateful for your help. Thank you very much for your help!
> > 
> > 
> > Hello! I encountered some issues while trying to obtain the code. I found out from your homepage that you are Chinese, can I communicate with you about it?
> 
> Of course.My QQ number is 3489574613,you can contact me.

thank you
