### ISSUE TITLE
The rgb_frames of the wear dataset

### ISSUE THREAD

**Issue by xgiaogiao** [masashi-hatano/MM-CDFSL#6]
Hello!Could you please provide the frame rate and any specific parameters or tools you used for extracting frames (e.g., resolution, frame sampling rate, etc.) about the wear dataset? This information would be extremely helpful in ensuring consistency with your original implementation.Thank you very much!

**Comment by masashi-hatano** [comment]
We convert the RGB video into frames with the same FPS as the video capture and then use the sampling rate indicated in the config file for each dataset.
As for the resolution, we save the frames so that their height is 256 while keeping the aspect ratio.

**Comment by xgiaogiao** [comment]
Thank you very much!

**Comment by masashi-hatano** [comment]
It depends on the dataset (I think it is 60 FPS for the WEAR dataset, but I am not sure so please check the original paper if you are curious).
Anyway, you need to extract all frames contained in videos, as you cannot extract them with a higher FPS than the original video capture setting.

The following is the function for extracting image frames just in case.
```
def extract_image_frame(video_path, output_dir="/path/to/output_dir"):
    print(f"processing {str(video_path)}...")
    video_name = Path(video_path).name.replace(".mp4", "")
    output_frame_dir = Path(output_dir) / video_name
    os.makedirs(output_frame_dir, exist_ok=True)
    video = cv2.VideoCapture(str(video_path))
    
    frame_rate = video.get(cv2.CAP_PROP_FPS)
    frame_width = video.get(cv2.CAP_PROP_FRAME_WIDTH)
    frame_height = video.get(cv2.CAP_PROP_FRAME_HEIGHT)
    
    target_height = 256
    target_width = int(frame_width*(target_height/frame_height))

    frame_num = 0

    while video.isOpened():
        ret, frame = video.read()

        frame_num += 1
        if ret:
            # rgb_center_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (target_width, target_height))
            cv2.imwrite(
                f"{output_frame_dir}/{str(frame_num).zfill(6)}.jpg", frame
            )
        else:
            break
```

**Comment by xgiaogiao** [comment]
Thank you very much for your reply!Thank you very much for your work and help ! I would greatly appreciate it!
