### ISSUE TITLE
About Pretrain

### ISSUE THREAD

**Issue by lzjjia** [masashi-hatano/MM-CDFSL#8]
Hello! 
how can i download the "videomae_small_patch16_224.pth"?  I found this Configuration in your "pretrain_trainer.yaml" file!
I am new researcher，Can you help me？Thanks!

**Comment by masashi-hatano** [comment]
You can download it from the Model Zoo in README.
If you are interested in other videomae models, please visit [original github code](https://github.com/MCG-NJU/VideoMAE/blob/main/MODEL_ZOO.md).

**Comment by lzjjia** [comment]
thanks for your reply! And what is the difference among pretrain_videomae_small_patch16_224 、 pretrain_videomae_base_patch16_224  and pretrain_videomae_large_patch16_224 ? Should I read the VideoMAE paper?

**Comment by masashi-hatano** [comment]
It indicates the size of ViT.
It's better to read the paper as the pre-training part of our method is based on VideoMAE.

**Comment by lzjjia** [comment]
thank you！

**Comment by xixi00001** [comment]
> Hello! how can i download the "videomae_small_patch16_224.pth"? I found this Configuration in your "pretrain_trainer.yaml" file! I am new researcher，Can you help me？Thanks!

Hello, have you successfully run the code yet? Are you Chinese? Can we add each other on WeChat for further communication?
